//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokTakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbStokTakipEntities2 : DbContext
    {
        public DbStokTakipEntities2()
            : base("name=DbStokTakipEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TABLE_ADMIN> TABLE_ADMIN { get; set; }
        public virtual DbSet<TABLE_BANKA> TABLE_BANKA { get; set; }
        public virtual DbSet<TABLE_DEPARTMAN> TABLE_DEPARTMAN { get; set; }
        public virtual DbSet<TABLE_FATURABILGI> TABLE_FATURABILGI { get; set; }
        public virtual DbSet<TABLE_FATURADETAY> TABLE_FATURADETAY { get; set; }
        public virtual DbSet<TABLE_KATEGORI> TABLE_KATEGORI { get; set; }
        public virtual DbSet<TABLE_MARKA> TABLE_MARKA { get; set; }
        public virtual DbSet<TABLE_MUSTERI> TABLE_MUSTERI { get; set; }
        public virtual DbSet<TABLE_NOTLAR> TABLE_NOTLAR { get; set; }
        public virtual DbSet<TABLE_OZELLIKLER> TABLE_OZELLIKLER { get; set; }
        public virtual DbSet<TABLE_SEHIR> TABLE_SEHIR { get; set; }
        public virtual DbSet<TABLE_SORUMLU> TABLE_SORUMLU { get; set; }
        public virtual DbSet<TABLE_URUN> TABLE_URUN { get; set; }
        public virtual DbSet<TABLE_URUNHAREKET> TABLE_URUNHAREKET { get; set; }
    }
}
