//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunStokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_SORUMLU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TABLE_SORUMLU()
        {
            this.TABLE_FATURABILGI = new HashSet<TABLE_FATURABILGI>();
            this.TABLE_URUNHAREKET = new HashSet<TABLE_URUNHAREKET>();
        }
    
        public int ID { get; set; }
        public string SORUMLU_AD { get; set; }
        public string SORUMLU_SOYAD { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public string FOTOGRAF { get; set; }
        public string MAIL { get; set; }
        public string TELEFON { get; set; }
    
        public virtual TABLE_DEPARTMAN TABLE_DEPARTMAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLE_FATURABILGI> TABLE_FATURABILGI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLE_URUNHAREKET> TABLE_URUNHAREKET { get; set; }
    }
}
